version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: furniro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço Node.js com Nest.js
  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: furniro
      SERVER_PORT: 3001
    command: sh -c "npm install && npm run dev"

  # Serviço do frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
